import sys
from datetime import datetime
from core.config import Config
from core.logger import setup_logger
from providers.aws import AWSProvider
from utils.ssh_config import SSHConfigGenerator

def main():
    logger = setup_logger()

    config = Config.load_from_env()
    
    provider = AWSProvider()
    generator = SSHConfigGenerator(config)

    start_time = datetime.now()
    instances = provider.get_instances()
    
    if not instances:
        logger.warning("No running instances found.")
        sys.exit(0)

    config_content = [
        "# Auto-generated by ksh plugin (Python)",
        f"# Date: {start_time}",
        ""
    ]
    
    synced_count = 0
    for instance in instances:
        entry = generator.generate_entry(instance)
        if entry:
            config_content.append(entry)
            synced_count += 1

    try:
        with open(config.ec2_config_file, "w") as f:
            f.write("\n".join(config_content))
        print(f"\033[KSuccess! Synced {synced_count} instances from AWS in {(datetime.now() - start_time).total_seconds():.2f}s.")
        # print(f"Config file: {config.ec2_config_file}")
    except IOError as e:
        logger.error(f"Error writing config file: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()
